### ISSUE TITLE
ThreeWayBinding is absent

### ISSUE THREAD

**Issue by jbilcke** [edmulraney/aurelia-fire#1]
Hi,

It looks like there is a missing file: `src/three-way-binding.js` 

If you have it on your side, could you maybe add it to the repo?

(FirebaseArray is working well, by the way :+1:)

**Comment by edmulraney** [comment]
Hi,

Thanks for spotting this jbilcke. I've added the missing file now.

**Comment by jbilcke** [comment]
Nice, thank you!
